package com.S2M.TransactionsBatchUseCase.Writer;
import com.S2M.TransactionsBatchUseCase.Entity.Repport.Trasaction.FeeInfo;
import lombok.RequiredArgsConstructor;
import org.springframework.batch.item.Chunk;
import org.springframework.batch.item.ItemWriter;
import org.springframework.batch.item.database.BeanPropertyItemSqlParameterSourceProvider;
import org.springframework.batch.item.database.JdbcBatchItemWriter;
import org.springframework.batch.item.database.builder.JdbcBatchItemWriterBuilder;

import javax.sql.DataSource;

@RequiredArgsConstructor
public class FeeInfoJdbcWriter implements ItemWriter<FeeInfo> {

    private final DataSource dataSource;

    // SQL statement to insert data into the TX_FEE_INFO table.
    // Column names match the @Column(name = "...") annotations in the FeeInfo entity.
    // Named parameters (:propertyName) match the property names in the FeeInfo entity.
    // The 'ID' column is omitted as it's auto-generated by a sequence.
    private static final String INSERT_FEE_INFO_SQL =
            "INSERT INTO TX_FEE_INFO (" +
                    "   id, FEE_AMOUNT, FEE_CODE, FEE_CURRENCY, FEE_DESC, FEE_SIGN, " +
                    "   FEE_TYPE, INST_REF, TX_ID" +   // TX_ID is the FK to TRANSACTION
                    ") VALUES (" +
                    "   nextval('FEE_INFO_SEQ'), :feeAmount, :feeCode, :feeCurrency, " +
                    "   :feeDescription, :feeSign, :feeType, :institutionReference, :transactionId" +
                    ")";

    private JdbcBatchItemWriter<FeeInfo> delegate;

    private void initDelegate() {
        if (delegate == null) {
            delegate = new JdbcBatchItemWriterBuilder<FeeInfo>()
                    .dataSource(this.dataSource)
                    .sql(INSERT_FEE_INFO_SQL)
                    .itemSqlParameterSourceProvider(new BeanPropertyItemSqlParameterSourceProvider<>())
                    .build();
            delegate.afterPropertiesSet();
        }
    }

    @Override
    public void write(Chunk<? extends FeeInfo> chunk) throws Exception {
        initDelegate();
        delegate.write(chunk);
    }
}
