package com.S2M.CSVImport.Mapper;

import com.S2M.CSVImport.Entity.Trasaction.FeeInfo;
import org.springframework.batch.item.file.mapping.FieldSetMapper;
import org.springframework.batch.item.file.transform.FieldSet;

public class FeeInfoFileFieldSetMapper implements FieldSetMapper<FeeInfo> {

    @Override
    public FeeInfo mapFieldSet(FieldSet fieldSet) {
        if (fieldSet == null) {
            return null;
        }

        FeeInfo.FeeInfoBuilder builder = FeeInfo.builder();

        // We do not read 'id' as it's auto-generated by the database sequence.
        builder.feeAmount(fieldSet.readBigDecimal("feeAmount"));
        builder.feeCode(fieldSet.readString("feeCode"));
        builder.feeCurrency(fieldSet.readString("feeCurrency"));
        builder.feeDescription(fieldSet.readString("feeDescription"));
        builder.feeSign(fieldSet.readString("feeSign"));
        builder.feeType(fieldSet.readString("feeType"));
        builder.institutionReference(fieldSet.readString("institutionReference"));
        builder.transactionId(fieldSet.readLong("transactionId")); // This comes from the CSV

        return builder.build();
    }
}
